# Generated by Django 2.2.3 on 2019-08-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='good',
            field=models.ManyToManyField(to='good.Good'),
        ),
    ]
