# Generated by Django 2.2.3 on 2019-08-06 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_good'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='good',
            new_name='goods',
        ),
    ]
