# Generated by Django 2.2.3 on 2019-08-06 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20190806_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 8, 6, 13, 8, 48, 803530)),
        ),
    ]
