# Generated by Django 2.2.3 on 2019-08-06 13:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('applications', '0005_auto_20190806_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 8, 6, 13, 22, 21, 356321)),
        ),
    ]
