# Generated by Django 2.2.3 on 2019-08-06 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
            preserve_default=False,
        ),
    ]
